export type Guide = {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  coverImage: string;
  date: string;
  readTime: string;
  category: string;
};

export const guidesData: Guide[] = [
  {
    slug: 'secure-sme-financing-nigeria',
    title: 'How to Secure SME Financing in Nigeria',
    excerpt: 'A step-by-step guide to understanding working capital, LPO financing, and getting the funds your business needs to grow.',
    content: `
## The Importance of SME Financing
Small and Medium Enterprises (SMEs) are the lifeblood of the Nigerian economy. However, accessing capital remains one of the biggest challenges for business owners. Whether you need to execute a new contract, purchase inventory, or manage cash flow, having the right financial partner is crucial.

### Types of SME Financing Available

#### 1. LPO Financing
If you have secured a Local Purchase Order (LPO) from a reputable organization but lack the funds to execute it, LPO financing is your best bet. Swiftbanq provides up to 70% of the contract value to help you deliver on time.

#### 2. Invoice Discounting
Waiting 30 to 90 days for an invoice to be paid can cripple your cash flow. Invoice discounting allows you to access immediate cash by selling your unpaid invoices at a small discount.

#### 3. Working Capital Loans
These are short-term loans designed to cover everyday operational expenses like payroll, rent, and inventory purchases.

### How to Prepare for an Application
To increase your chances of approval, ensure you have:
- Clean and up-to-date financial records.
- A registered business with the CAC.
- Six months of bank statements demonstrating cash flow.
- A clear purpose for the loan.

At Swiftbanq, we've simplified this process. Our SME financing options are designed to be fast, fair, and tailored to your specific business cycle.
    `,
    coverImage: '/swiftbanq-office-4.jpg',
    date: '2026-05-20',
    readTime: '5 min read',
    category: 'SME Financing'
  },
  {
    slug: 'ultimate-guide-asset-equipment-financing',
    title: 'The Ultimate Guide to Asset & Equipment Financing',
    excerpt: 'Learn how to acquire vehicles, machinery, and IT infrastructure without draining your working capital.',
    content: `
## Why Finance Equipment Instead of Buying Outright?
For many businesses, acquiring new equipment is a major expense that can deplete cash reserves. Asset financing allows you to spread the cost of the asset over its useful life, freeing up capital for other investments.

### What Can You Finance?
- **Vehicles & Fleet:** Delivery vans, corporate cars, and logistics trucks.
- **Office Equipment:** Laptops, servers, and communication systems.
- **Industrial Machinery:** Manufacturing equipment, generators, and specialized tools.

### Benefits of Asset Financing
1. **Preserve Cash Flow:** Keep your working capital intact for emergencies and daily operations.
2. **Tax Advantages:** Lease payments can often be deducted as business expenses.
3. **Stay Updated:** Easily upgrade to the latest technology without being stuck with obsolete equipment.

### The Swiftbanq Approach
Swiftbanq offers flexible repayment terms ranging from 12 to 36 months, allowing you to match your payments with the revenue generated by the asset. We finance both new and used equipment, ensuring you get exactly what you need to scale.
    `,
    coverImage: '/image-3.jpg',
    date: '2026-05-18',
    readTime: '4 min read',
    category: 'Asset Financing'
  },
  {
    slug: 'navigating-digital-lending',
    title: 'Navigating Digital Lending: What You Need to Know',
    excerpt: 'Everything you need to know about getting a personal loan quickly and safely as a salary earner.',
    content: `
## The Rise of Digital Lending
Gone are the days of endless paperwork and weeks of waiting for loan approvals. Digital lending has revolutionized how individuals access credit, making it faster and more convenient than ever.

### What is a Digital Personal Loan?
A digital personal loan is an unsecured loan provided entirely online. It is primarily designed for salary earners who need quick cash for emergencies, rent, school fees, or personal projects.

### What to Look Out For
While digital lending is convenient, it's important to be a smart borrower:
- **Interest Rates:** Understand the total cost of the loan, including any hidden fees.
- **Repayment Terms:** Ensure the monthly repayment fits comfortably within your budget.
- **Data Privacy:** Only use licensed and reputable lenders to protect your personal information.

### Swiftbanq Digital Lending
We offer instant disbursement personal loans with highly competitive rates. Our process is transparent—no hidden charges, flexible repayment terms (up to 12 months), and top-tier data security. Your financial well-being is our priority.
    `,
    coverImage: '/images/home-family.jpg',
    date: '2026-05-15',
    readTime: '3 min read',
    category: 'Personal Finance'
  },
  ...Array.from({ length: 11 }).map((_, i) => ({
    slug: `dummy-guide-${i + 1}`,
    title: `Financial Growth Strategy ${i + 1}: Expert Tips`,
    excerpt: `Discover essential tips and strategies for scaling your business and optimizing your financial health in today's economy.`,
    content: `
## Overview
This is a dummy guide to demonstrate pagination. It contains placeholder text regarding financial strategies, business growth, and asset management.

### Key Takeaways
- Always monitor your cash flow.
- Invest in the right assets.
- Leverage digital lending when necessary.
    `,
    coverImage: i % 2 === 0 ? '/swiftbanq-office-4.jpg' : '/image-3.jpg',
    date: `2026-05-0${(i % 9) + 1}`,
    readTime: `${(i % 5) + 3} min read`,
    category: i % 2 === 0 ? 'Business Tips' : 'Finance'
  }))
];
